name: Dice
version: '${version}'
main: com.github.majisyou.dice.Dice
api-version: 1.18
authors: [ majisyou ]
description: minecerft-dice

commands:
  setdice:
    description: ダイスコマンド
    usage: コマンド失敗
    permission: dice_user

  setdicetest:
    description: ダイステスト
    usage: コマンド失敗
    permission: dice_op

  setc_lo:
    description: チンチロリンをするコマンド
    usage: コマンド失敗
    permission: dice_master

  give_dice:
    description: プリンスダイスをもらえるコマンド
    usage: コマンド失敗
    permission: dice_op

permissions:
  dice_user:
    description: default
    default: true